[package]
name = "mbed"
version = "0.1.0"
authors = ["Anshul Kumrawat <anshulkumrawat120937@gmail.com>","Darshika tiwari <darshikatiwari29@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
