[package]
name = "asn1_parse"
version = "0.1.0"
authors = ["pallavi7naik"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
